In [3]:
import sqlite3
import pandas as pd

# 1. 锁定你刚才灌好数据的硬盘文件
db_path = r"C:\projects\machinelearning_study\raw_data\datacamp\SQL\world.db"
conn = sqlite3.connect(db_path)

# ========================================================
# 2. 【你的 SQL 练习区】把你的 SQL 代码丢进下面这个三引号里
# ========================================================
sql_cities = "SELECT * FROM cities;"
df_cities = pd.read_sql_query(sql_cities,conn)

sql_countries = "SELECT * FROM countries;"
df_countries = pd.read_sql_query(sql_countries,conn)

sql_languages = "SELECT * FROM languages;"
df_languages = pd.read_sql_query(sql_languages,conn)

print(f"第一张表cities:")
display(df_cities)

print(f"第二张表countries:")
display(df_countries)

print(f"第三张表languages:")
display(df_languages)

第一张表cities:

            name country_code  population  urbanarea_pop        capital
0        Beijing          CHN    21000000       21000000        Beijing
1       Shanghai          CHN    24000000       24000000
2      New Delhi          IND    16000000       16000000      New Delhi
3         Mumbai          IND    12000000       12000000
4       New York          USA     8000000        8000000
5  Washington DC          USA      700000         700000  Washington DC
6      Singapore          SGP     5600000        5600000      Singapore
7         Monaco          MCO       38000          38000         Monaco

第二张表countries:

  code           name      continent
0  CHN          China           Asia
1  IND          India           Asia
2  USA  United States  North America
3  SGP      Singapore           Asia
4  MCO         Monaco         Europe
5  ATL       Atlantis           None
6  WKD        Wakanda           None
7  LIL       Lilliput           None

第三张表languages:

    id country_code  lang_name
0    1          CHN   Mandarin
1    2          CHN  Cantonese
2    3          CHN    Tibetan
3    4          IND      Hindi
4    5          IND    English
5    6          IND    Bengali
6    7          USA    English
7    8          USA    Spanish
8    9          SGP    English
9   10          SGP      Malay
10  11          SGP   Mandarin
11  12          SGP      Tamil
12  13          MCO     French